name: curl_generator
description: A Dart package to create simple curl (bash) with params, headers and body.
version: 1.0.1
homepage: https://b1101-portfolio.web.app
repository: https://github.com/P-B1101/curl_generator

environment:
  sdk: ">=2.18.0 <4.0.0"

# dependencies:

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0

